title: Jekyll Actions Guide
description: "How to setup Github Pages + Actions for use with Jekyll 4"

url: "https://meleu.github.io"
baseurl: "/jekyll-actions-test"

github_username: meleu

markdown: kramdown
theme: minima
plugins:
  - jekyll-timeago
